// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALXCZkc_f9Fsi0kprI1HVhPX7X3smUg-o',
    appId: '1:341347912772:web:19af8b0a79fd6023b24011',
    messagingSenderId: '341347912772',
    projectId: 'sendy-fc0ed',
    authDomain: 'sendy-fc0ed.firebaseapp.com',
    storageBucket: 'sendy-fc0ed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM7F710kjbjPZ96QS_lxFIs6QtZu657EY',
    appId: '1:341347912772:android:3e25502b4cb83eb1b24011',
    messagingSenderId: '341347912772',
    projectId: 'sendy-fc0ed',
    storageBucket: 'sendy-fc0ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2Oqjo2t_twPYr5R5Q2VtDiab9ArUEZ7E',
    appId: '1:341347912772:ios:7e82155122d53dc7b24011',
    messagingSenderId: '341347912772',
    projectId: 'sendy-fc0ed',
    storageBucket: 'sendy-fc0ed.firebasestorage.app',
    iosBundleId: 'com.example.sendy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2Oqjo2t_twPYr5R5Q2VtDiab9ArUEZ7E',
    appId: '1:341347912772:ios:7e82155122d53dc7b24011',
    messagingSenderId: '341347912772',
    projectId: 'sendy-fc0ed',
    storageBucket: 'sendy-fc0ed.firebasestorage.app',
    iosBundleId: 'com.example.sendy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALXCZkc_f9Fsi0kprI1HVhPX7X3smUg-o',
    appId: '1:341347912772:web:fe9160ed219474cfb24011',
    messagingSenderId: '341347912772',
    projectId: 'sendy-fc0ed',
    authDomain: 'sendy-fc0ed.firebaseapp.com',
    storageBucket: 'sendy-fc0ed.firebasestorage.app',
  );
}
